/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a0207cc9a94ea7d3997e9ccaa436348d)
interface __BaseEnv_Env {
	SHARES: R2Bucket;
	UPLOAD_RATE_LIMITER: RateLimit;
	PICKUP_IP_RATE_LIMITER: RateLimit;
	PICKUP_CODE_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	SHARE_TTL_SECONDS: "604800";
	PICKUP_TTL_SECONDS: "600";
	PICKUP_CODES: DurableObjectNamespace<import("./worker/index").PickupCode>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "PickupCode";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
