/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1fa1e285d02b939cb00fdbec9454d05d)
interface __BaseEnv_Env {
	SHARES: R2Bucket;
	UPLOAD_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	SHARE_TTL_SECONDS: "604800";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
